excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://agarciatv.github.io
title: Aaron Garcia
tagline: Make stuff, take risks and be awesome!
description: This blog is for those who enjoy nerdy and creative things!
paginate: 5
