excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://agarciatv.github.io
title: Aaron Garcia
tagline: Video Production, Photography, Web Development, Marketing
description: This blog is for those who enjoy technical and creative things!
paginate: 5
