excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://agarciatv.github.io
title: Aaron Garcia
tagline: Technically Creative
description: This blog is for those who enjoy technical and creative things!
paginate: 5
