excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://agarciatv.github.io
title: Aaron's Blog
tagline: Dream, invent, discover and share!
description: This blog is for those who enjoy nerdy and creative things!
paginate: 5
